### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s3-evaluacion-intermedia-claraharguindey#1]
Well done @claraharguindey !!!

Tips to improve the exercise:

- [x] We should avoid storing props on state when possible!
- [x] 'Pokelist' component should paint the list (ul + .map) and 'Pokemon' component should paint a pokemon card
- [x] Alternative text of pokemon image could include the pokemon name
- [x] Finish styles (one file per component)
- [x] Review metadata on index.html (lang, title...)
- [x] Clean and indent

Go for it!

**Comment by claraharguindey** [comment]
Ok, @nasivuela s! Thank you for check my exercise out.
I've follow your tips and improve my code, chek it out please! :)

**Comment by nasivuela** [comment]
Good work!

![](https://media.giphy.com/media/jL6OeIhk3zPi/giphy.gif)
